### ISSUE TITLE
Nice job.

### ISSUE THREAD

**Issue by Thespikedballofdoom** [shinrax2/OpenInSteam#4]
Kicks every other extension that tries to do this's ass.
Out of curiosity, why isn't it on the chrome webstore if it works?

**Comment by Thespikedballofdoom** [comment]
Also how come all those excluded URLs are excluded?

**Comment by shinrax2** [comment]
thanks alot for the kind words but you have to thank @Strappazzon for the neat look of it

was just to lazy to release it on the chrome store but i will upload there soon

the excludes are there because either
1. its pointless to have the button on login pages ( and it might break steam login for 3rd party website login)
2. the script for steam community pages is special and is only meant to run on certain urls
